pages:
  services: 
    - docker:dind
  script:
  - docker run --rm -it -v $(pwd):/docs miroadamy/mkdocs-material:latest build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master
