site_name: My Docs
repo_url: https://github.com/example/repository/
repo_name: SOME-NAME
site_description: My Site description
site_author: Miro A
copyright: (c) 2020 Miro A

nav:
    - Home: index.md
    - About: about.md
theme: 
    name: material

markdown_extensions:
    - admonition
    - codehilite  
    - toc:
        permalink: True
    - sane_lists

plugins:
    - search

